INSERT INTO projects (name, slug, status, collaborators) VALUES
('dynamic synergy initiative', 'dynamic-synergy-initiative', 'in-progress', ARRAY[1, 2]),
('future metrics matrix', 'future-metrics-matrix', 'completed', ARRAY[3]),
('visionary infrastructure alliance', 'visionary-infrastructure-alliance', 'completed', ARRAY[1]),
('innovative integration group', 'innovative-integration-group', 'in-progress', ARRAY[2, 3]),
('scalable response system', 'scalable-response-system', 'in-progress', ARRAY[1, 3]),
('modular innovation strategy', 'modular-innovation-strategy', 'completed', ARRAY[2]),
('virtual optimization protocol', 'virtual-optimization-protocol', 'completed', ARRAY[2, 3]),
('tactical synergy workflow', 'tactical-synergy-workflow', 'in-progress', ARRAY[3]),
('holistic solution design', 'holistic-solution-design', 'in-progress', ARRAY[1]),
('proactive strategy platform', 'proactive-strategy-platform', 'completed', ARRAY[1, 2]),
('sustainable process initiative', 'sustainable-process-initiative', 'in-progress', ARRAY[3]),
('global delivery structure', 'global-delivery-structure', 'completed', ARRAY[2]),
('enterprise vision model', 'enterprise-vision-model', 'in-progress', ARRAY[1, 3]),
('streamlined function hub', 'streamlined-function-hub', 'completed', ARRAY[2]),
('collaborative evolution protocol', 'collaborative-evolution-protocol', 'in-progress', ARRAY[1, 2]),
('innovative delivery alliance', 'innovative-delivery-alliance', 'completed', ARRAY[3]),
('nextgen architecture strategy', 'nextgen-architecture-strategy', 'in-progress', ARRAY[1, 3]),
('modular impact group', 'modular-impact-group', 'completed', ARRAY[2]),
('visionary response initiative', 'visionary-response-initiative', 'in-progress', ARRAY[1]),
('agile development matrix', 'agile-development-matrix', 'completed', ARRAY[1, 2, 3]),
('scalable integration network', 'scalable-integration-network', 'in-progress', ARRAY[2, 3]),
('future synergy blueprint', 'future-synergy-blueprint', 'completed', ARRAY[3]),
('optimized vision hub', 'optimized-vision-hub', 'in-progress', ARRAY[1]),
('intelligent function model', 'intelligent-function-model', 'completed', ARRAY[1, 2]),
('nextgen synergy protocol', 'nextgen-synergy-protocol', 'in-progress', ARRAY[2]),
('proactive solution alliance', 'proactive-solution-alliance', 'completed', ARRAY[3]),
('strategic innovation platform', 'strategic-innovation-platform', 'in-progress', ARRAY[1, 2]),
('sustainable response design', 'sustainable-response-design', 'completed', ARRAY[2]),
('virtual structure model', 'virtual-structure-model', 'in-progress', ARRAY[1]),
('dynamic strategy workflow', 'dynamic-strategy-workflow', 'completed', ARRAY[1, 3]);
